### ISSUE TITLE
Issue gets enrollment results

### ISSUE THREAD

**Issue by isaac-galvan** [pfptcommunity/psat-api-python#1]
Hello, I am using your Querying Enrollments Reports example in the README file.
I get the following error:
> requests.exceptions.InvalidHeader: Header part (<Version.V3: 'v0.3.0'>) from ('x-apikey-token', <Version.V3: 'v0.3.0'>) must be of type str or bytes, not <enum 'Version'>

Please take a look. Thank you! @ludvikjerabek

**Comment by ludvikjerabek** [comment]
Thanks for letting me know, I will take a look shortly. Can you pass the exact test code that is failing? Also can you provide the version of Python?

**Comment by ludvikjerabek** [comment]
Documentation has been updated to reflect proper usage. Please see release 3.0.2 and updated usage information it's probably best to see https://github.com/pfptcommunity/psat-api-python/tree/master/example for proper usage. Thanks again for the bug report.
